/******** DO NOT EDIT THIS FILE ********/
#include "../mutex_lockvar.h"
#include "test_mutex_lockvar.h"
#include "procs4tests.h"

static void* test_setup(const MunitParameter params[], void* user_data) {
    return new_test_procs();
}

static void test_tear_down(void* fixture) {
    delete_test_procs((test_procs_t*) fixture);
}

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static mutex_t* assert_mu_new(proc_t* p) {    
    mutex_t* m = mu_new(p);
    
    assert_not_null(m);
    assert_not_null(m->addr);
    mutex_lockvar_t* lock = (mutex_lockvar_t*) m->addr;
    assert_int(*lock, ==, 0);

    return m;
}

static mutex_t* assert_mu_enter(proc_t* p) {
    mutex_t* m = assert_mu_new(p);

    mutex_lockvar_t* lock = (mutex_lockvar_t*) m->addr;
    assert_int(*lock, ==, 0);
    
    mu_enter(m);
    assert_int(*lock, ==, 1);
    
    *lock = 0;
    
    return m;
}

static mutex_t* assert_mu_leave(proc_t* p) {
    mutex_t* m = assert_mu_new(p);

    mutex_lockvar_t* lock = (mutex_lockvar_t*) m->addr;
    
    *lock = 1;

    mu_leave(m);
    assert_int(*lock, ==, 0);
    
    return m;
}

static MunitResult test_mu_new(const MunitParameter params[], 
    void* fixture) {
    test_procs_t* p = fixture;
    
    mutex_t* min = assert_mu_new(p->pin);
    mutex_t* mni = assert_mu_new(p->pni);
    
    mu_delete(mni);
    
    mu_delete(min);
        
    return MUNIT_OK;
}   
    
static MunitResult test_mu_enter(const MunitParameter params[], 
    void* fixture) {
    test_procs_t* p = fixture;
    
    mutex_t* min = assert_mu_enter(p->pin);
    mutex_t* mni = assert_mu_enter(p->pni);

    mu_delete(min);
    mu_delete(mni);

    return MUNIT_OK;
}

static MunitResult test_mu_leave(const MunitParameter params[], 
    void* fixture) {
    test_procs_t* p = fixture;
    
    mutex_t* min = assert_mu_leave(p->pin);
    mutex_t* mni = assert_mu_leave(p->pni);

    mu_delete(min);
    mu_delete(mni);

    return MUNIT_OK;
}
