/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_shobject_name.h - structures and function declarations for unit tests
 * of the shobject_name function.
 * 
 */  
#ifndef _TEST_SHOBJECT_NAME_H
#define _TEST_SHOBJECT_NAME_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit.h"

static MunitResult test_shobject_name(const MunitParameter params[],
    void* fixture);
    
static MunitTest tests[] = {
    { "/test_shobject_name", test_shobject_name, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_shobject_name", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif