/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_proc.h - structures and function declarations for unit tests
 * of proc functions.
 * 
 */  
#ifndef _TEST_UTIL_H
#define _TEST_UTIL_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit.h"

static MunitResult test_proc_init(const MunitParameter params[],
    void* fixture);
    
static MunitTest tests[] = {
    { "/test_proc_init", test_proc_init, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_util", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif