/******** DO NOT EDIT THIS FILE ********/
#include <stdio.h>
#include <unistd.h>
#include "test_proc.h"
#include "../proc.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static MunitResult test_proc_init(const MunitParameter params[], 
    void* fixture) {        
    proc_t* p;
    
    char* argv0[] = {"arg0", "0", "1"};    
    p = proc_init(3, argv0, 0);
    assert_int(strncmp(p->name, "arg0", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 0);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 20);
    assert_int(p->crit_work.max, ==, 40);
    assert_int(p->noncrit_work.min, ==, 20);
    assert_int(p->noncrit_work.max, ==, 40);
    proc_delete(p);
    
    char* argv1[] = {"arg1", "1", "10", "-ds", "1"};    
    p = proc_init(5, argv1, 0);
    assert_int(strncmp(p->name, "arg1", 4), ==, 0);
    assert_int(p->id, ==, 1);
    assert_int(p->jobs, ==, 10);
    assert_int(p->delay_start, ==, 1);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 20);
    assert_int(p->crit_work.max, ==, 40);
    assert_int(p->noncrit_work.min, ==, 20);
    assert_int(p->noncrit_work.max, ==, 40);
    proc_delete(p);

    char* argv2[] = {"arg2", "0", "1", "-de", "2", "-w"};    
    p = proc_init(6, argv2, 0);
    assert_int(strncmp(p->name, "arg2", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 0);
    assert_int(p->delay_exit, ==, 2);
    assert_int(p->crit_work.min, ==, 20);
    assert_int(p->crit_work.max, ==, 40);
    assert_int(p->noncrit_work.min, ==, 20);
    assert_int(p->noncrit_work.max, ==, 40);
    proc_delete(p);

    char* argv3[] = {"arg3", "0", "1", "-w", "1", "2", "3", "4"};    
    p = proc_init(8, argv3, 0);
    assert_int(strncmp(p->name, "arg3", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 0);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 3);
    assert_int(p->noncrit_work.max, ==, 4);
    proc_delete(p);

    char* argv4[] = {"arg4", "0", "1", "-w", "1", "2"};    
    p = proc_init(6, argv4, 0);
    assert_int(strncmp(p->name, "arg4", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 0);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 1);
    assert_int(p->noncrit_work.max, ==, 2);
    proc_delete(p);

    char* argv5[] = {"arg5", "0", "1", "-ds", "1", "-w", "1", "2"};    
    p = proc_init(8, argv5, 0);
    assert_int(strncmp(p->name, "arg5", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 1);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 1);
    assert_int(p->noncrit_work.max, ==, 2);
    proc_delete(p);

    char* argv6[] = {"arg6", "0", "1", "-ds", "1", "-de", "2", "-w", "1", "2"};    
    p = proc_init(10, argv6, 0);
    assert_int(strncmp(p->name, "arg6", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 1);
    assert_int(p->delay_exit, ==, 2);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 1);
    assert_int(p->noncrit_work.max, ==, 2);
    proc_delete(p);

    char* argv7[] = {"arg7", "0", "1", "-ds", "1", "-w", "1", "2", "7", "8"};    
    p = proc_init(10, argv7, 0);
    assert_int(strncmp(p->name, "arg7", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 1);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 7);
    assert_int(p->noncrit_work.max, ==, 8);
    proc_delete(p);

    char* argv8[] = {"arg8", "0", "1", "-ds", "1", "-de", "2", 
        "-w", "1", "2", "7", "8"};    
    p = proc_init(12, argv8, 0);
    assert_int(strncmp(p->name, "arg8", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 1);
    assert_int(p->delay_exit, ==, 2);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 7);
    assert_int(p->noncrit_work.max, ==, 8);
    proc_delete(p);

    char* argv9[] = {"arg9", "0", "1", "-de", "1", "-w", "1", "2", "7", "8"};    
    p = proc_init(10, argv9, 0);
    assert_int(strncmp(p->name, "arg9", 4), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 0);
    assert_int(p->delay_exit, ==, 1);
    assert_int(p->crit_work.min, ==, 1);
    assert_int(p->crit_work.max, ==, 2);
    assert_int(p->noncrit_work.min, ==, 7);
    assert_int(p->noncrit_work.max, ==, 8);
    proc_delete(p);

    char* argv10[] = {"arg10", "0", "1", "-ne", "-s", "1", "2", "7", "8"};    
    p = proc_init(9, argv10, 0);
    assert_int(strncmp(p->name, "arg10", 5), ==, 0);
    assert_int(p->id, ==, 0);
    assert_int(p->jobs, ==, 1);
    assert_int(p->delay_start, ==, 0);
    assert_int(p->delay_exit, ==, 0);
    assert_int(p->crit_work.min, ==, 20);
    assert_int(p->crit_work.max, ==, 40);
    assert_int(p->noncrit_work.min, ==, 20);
    assert_int(p->noncrit_work.max, ==, 40);
    proc_delete(p);

    char* argv11[] = {"arg11", "-1", "1"};    
    p = proc_init(3, argv11, 0);
    assert_null(p);

    char* argv12[] = {"arg12", "100", "1"};    
    p = proc_init(3, argv12, 0);
    assert_null(p);

    char* argv13[] = {"arg13", "99", "1"};    
    p = proc_init(3, argv13, 0);
    assert_not_null(p);
    proc_delete(p);

    char* argv14[] = {"arg14", "99", "0"};    
    p = proc_init(3, argv14, 0);
    assert_null(p);

    return MUNIT_OK;
}   
    
    
