/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_job.h - structures and function declarations for unit tests
 * of job functions.
 * 
 */  
#ifndef _TEST_JOB_H
#define _TEST_JOB_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit.h"

static MunitResult test_job_is_equal(const MunitParameter params[],
    void* fixture);

static MunitTest tests[] = {
    { "/test_job_is_equal", test_job_is_equal, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_job", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif