/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_jobqueue_common.h - structures and function declarations for
 * common unit tests of jobqueue, ipc_jobqueue and sem_ipc_jobqueue functions.
 */  
#ifndef _TEST_JOBQUEUE_COMMON_H
#define _TEST_JOBQUEUE_COMMON_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include <stdbool.h>
#include "munit.h"
#include "../job.h"
#include "../jobqueue.h"

typedef struct test_jqueue {
    /* queue to test */
    void* q;
    /* pointers to queue functions to test */
    size_t (*capacity)(void*);
    bool (*is_full)(void*);
    bool (*is_empty)(void*);
    void (*enqueue)(void*, job_t);
    job_t (*dequeue)(void*);
    job_t (*peekhead)(void*);
    job_t (*peektail)(void*);
    /* additional fields for verification of queue's internal state in tests */
    int* head;
    int* tail;
    int* buf_size;
    job_t* jobs;
} test_jqueue_t;

void assert_init_jobqueue_state(jobqueue_t* jq);
MunitResult test_jqueue_capacity(test_jqueue_t* test_jq);
MunitResult test_jqueue_is_full(test_jqueue_t* test_jq);
MunitResult test_jqueue_is_empty(test_jqueue_t* test_jq);
MunitResult test_jqueue_enqueue_dequeue(test_jqueue_t* test_jq);
MunitResult test_jqueue_peekhead(test_jqueue_t* test_jq);
MunitResult test_jqueue_peektail(test_jqueue_t* test_jq);

#endif