/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_sem_ipc_jobqueue.h - structures and function declarations for unit tests
 * of sem_ipc_jobqueue functions.
 * 
 */  
#ifndef _TEST_JOB_QUEUE_H
#define _TEST_JOB_QUEUE_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit.h"

static MunitResult test_sem_ijq_new_delete(const MunitParameter params[],
    void* fixture);
static MunitResult test_sem_ijq_capacity(const MunitParameter params[], void* fixture);
static MunitResult test_sem_ijq_is_full(const MunitParameter params[], void* fixture);
static MunitResult test_sem_ijq_is_empty(const MunitParameter params[], void* fixture);
static MunitResult test_sem_ijq_peekhead(const MunitParameter params[], 
    void* fixture);
static MunitResult test_sem_ijq_peektail(const MunitParameter params[], 
    void* fixture);

/* two-process tests */
static MunitResult test_sem_ijq_2proc_enqueue_dequeue(
    const MunitParameter params[], void* fixture);
static MunitResult test_sem_ijq_2proc_peekhead(const MunitParameter params[], 
    void* fixture);
static MunitResult test_sem_ijq_2proc_peektail(const MunitParameter params[], 
    void* fixture);
static void* test_setup(const MunitParameter params[], void* user_data);
static void test_tear_down(void* fixture);

static MunitTest tests[] = {
    { "/test_sem_ijq_new_delete", test_sem_ijq_new_delete, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_sem_ijq_capacity", test_sem_ijq_capacity, test_setup,
        test_tear_down, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_sem_ijq_is_full", test_sem_ijq_is_full, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_sem_ijq_is_empty", test_sem_ijq_is_empty, test_setup,
        test_tear_down, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_sem_ijq_peekhead", test_sem_ijq_peekhead, test_setup,
        test_tear_down, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_sem_ijq_peektail", test_sem_ijq_peektail, test_setup,
        test_tear_down, MUNIT_TEST_OPTION_NONE, NULL },
        
    /* two-process tests */
    { "/test_sem_ijq_2proc_enqueue_dequeue", 
        test_sem_ijq_2proc_enqueue_dequeue, NULL, NULL, MUNIT_TEST_OPTION_NONE,
        NULL },
    { "/test_sem_ijq_2proc_peekhead", test_sem_ijq_2proc_peekhead, NULL,
        NULL, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_sem_ijq_2proc_peektail", test_sem_ijq_2proc_peektail, NULL,
        NULL, MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_ipc_jobqueue", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif