/******** DO NOT EDIT THIS FILE ********/
#include "test_job.h"
#include "../job.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static MunitResult test_job_is_equal(const MunitParameter params[], 
    void* fixture) { 
    
    for (int i = -1; i < 10; i++) {
        job_t j1 = { i, i };
        job_t j2 = { i, i };
        job_t j3 = { i - 1, i };
        job_t j4 = { i - 1, i };
        job_t j5 = { i, i + 1 };
        job_t j6 = { i, i + 1 };
        
        assert_true(job_is_equal(j1, j2));
        assert_true(job_is_equal(j3, j4));
        assert_true(job_is_equal(j5, j6));
        
        assert_false(job_is_equal(j1, j3));
        assert_false(job_is_equal(j1, j5));
        assert_false(job_is_equal(j3, j5));
    }
                
    return MUNIT_OK;
}   
