/******** DO NOT EDIT THIS FILE ********/
#include <stdlib.h>
#include "mutex_noop.h"

/* mutex.h has the specification of functions in this file */

/* 
 * In the no operation version of a mutex, just allocate a private 
 * mutex_noop_t on the heap that is not shared by processes
 */
mutex_t* mu_new(proc_t* proc) {
    return malloc(sizeof(mutex_noop_t));
}

/* 
 * This is a no operation version of mu_enter - it deliberately does nothing
 */
void mu_enter(mutex_t* mux) {
    return;
}

/* 
 * This is a no operation version of mu_enter - it deliberately does nothing
 */
void mu_leave(mutex_t* mux) {
    return;
}

/* 
 * This version of mu_delete just frees the memory allocated by mu_new
 */
void mu_delete(mutex_t* mux) {
    free(mux);
}
