/******** DO NOT EDIT THIS FILE ********/
#ifndef _MUTEX_NOOP_H
#define _MUTEX_NOOP_H
#include "mutex.h"  // implemented by mutex_noop.c


/* 
 * Definition of mutex_noop_t - the mutex type for the no-operation "solution"
 * to mutual exclusion. This solution is not even an attempt at a solution.
 * The mu_enter and mu_leave functions deliberately do nothing and therefore
 * permit unconstrained access to shared data for multiple processes. This 
 * can be used to demonstrate that application integrity will be violated if
 * there is no protected access to critical regions.
 *
 * Type alias:
 * mutex_noop_t is a type alias for an int
 *
 * See also:
 * mutex_noop.c - for implementation of the mutex.h interface
 */
typedef int mutex_noop_t;

#endif
