#!/bin/bash
#******** DO NOT EDIT THIS FILE ********#
# This shell script is for running simulations
# Type:
#    ./runsim.sh -h 
# for usage

num_jobs=150
cw_min=10   # consumer work range
cw_max=30
cds=50       # consumer delayed start (ms)
pde=1000     # init producer delayed start (ms)

: '
The following generated violations for lockvar and noop but overproduced
so need to slow down consumers
pde 1000, pw 20 40
cw 10 20, cds 100
'

sem_prefix=sem
bwait_prefix=bwait
bin=./bin
mux_type=noop
proc_pairs=1

function usage_exit {
    echo ""
    echo "usage: $0 [-h] [mutex_type process_pairs]"
    echo "    -h prints usage message and exits"
    echo "    mutex_type should be be one of:"
    echo "      noop: to use uncontrolled access to shared objects (default)"
    echo "      lockvar: to use the busy waiting \"lock\" variable mutex"
    echo "      peterson: to use Peterson's busy waiting solution"
    echo "      sem: to use a semaphore solution"
    echo "    process_pairs is the number of produce/consumer pairs and "
    echo "    should be between 1 and 4, the default is 1. If mutex_type is "
    echo "    specified, process_pairs must be specified"

    exit
}

if [ "$1" = "-h" ]; then 
    usage_exit
fi

if [ $# -ge 1 ]; then
    mux_type=$1
fi

if [ $# -ge 2 -a $mux_type != "peterson" ]; then 
    proc_pairs=$2
fi

if [ $proc_pairs -lt 1 ]; then
    proc_pairs=1
fi

if [ $proc_pairs -gt 4 ]; then
    proc_pairs=4
fi

if [ $mux_type = "sem" ]; then
    cons=${bin}/${sem_prefix}_consumer
    prod=${bin}/${sem_prefix}_producer
else
    cons=${bin}/${bwait_prefix}_consumer_${mux_type}
    prod=${bin}/${bwait_prefix}_producer_${mux_type}
fi    

if [ ! -f $cons ]; then
    echo "$cons does not exist"
    usage_exit
fi

if [ ! -f $prod ]; then
    echo "$prod does not exist"
    usage_exit
fi

rm -rf ./out

$prod 0 $num_jobs -i -de $pde &

for ((i = 1; i < $proc_pairs + 1; i++))
do
    $cons 1$i $num_jobs -ds $cds -w $cw_min $cw_max &
done

for ((i = 1; i < $proc_pairs; i++))
do
    $prod $i $num_jobs &
done

