/******** DO NOT EDIT THIS FILE ********/
/* This is the semaphore consumer application/simulation
 * Type:
 *      ./bin/sem_consumer
 * for usage
 *
 * The source code for the usage message is in proc_setup in proc.c.
 */
#include <stdio.h>
#include <unistd.h>
#include <stdbool.h>
#include "joblog.h"
#include "sem_ipc_jobqueue.h"

int main(int argc, char** argv) {
    // set queue constructor and destructor for setup 
    shobj_ctrl_t queue_ctrl = { (constructor_t) sem_ijq_new, 
                                (destructor_t) sem_ijq_delete };

    proc_t* proc = proc_setup(argc, argv, SEM_CONS_PROC, &queue_ctrl,
        NULL);
    
    if (jlog_init(proc) == -1) {
        proc_delete(proc);
        error_exit("could not initialise job log\n");
    }

    while (proc->jobs) {
        job_t j = sem_ijq_dequeue(proc->queue); // waits until not empty

        jlog_write_entry(proc, &j);
        
        proc->jobs--;
        
        do_noncritical_work(proc);     

        printf(".");
        fflush(stdout);
    }
    
    printf("\n");
    
    proc_teardown(proc);
    
    return EXIT_SUCCESS;
}
