#!/bin/bash
#******** DO NOT EDIT THIS FILE ********#
# This shell script is for updating a project distribution
# Type:
#   ./update.sh
# for usage 
assignment=csc2035-assignment1
src_dir="./"
cmd=tar
args=xfz
ext=tgz
extd=tmpext

if [ $# -lt 1 ]
then
    echo "usage: $0 [-t|-z] <from_dir>"
    echo "    -t for gzipped tar archive (default)"
    echo "    -z for zip archive"
    echo "    from_dir the directory containing the update archive"
    echo "    Do not add trailing slash (/) to the directory name"
        
    exit
fi

if [ $# -eq 1 ]
then 
    src_dir=$1
fi

if [ $# -eq 2 ]
then 
    if [ $1 = -z ]
    then
        cmd=unzip
        args=-oq
        ext=zip
    fi
    src_dir=$2
fi

mkdir ./$extd
cp $src_dir/${assignment}-update.${ext} ./$extd
cd ./$extd
$cmd $args ${assignment}-update.${ext}
cd ..
cp -R ./$extd/${assignment}-update/* .
rm -rf ./$extd
